// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMnV2LN8dBRwoOnpD1g4G3uP4j6jE1-ws',
    appId: '1:986850440427:web:c838c1d3b5ec988b19baae',
    messagingSenderId: '986850440427',
    projectId: 'geofencing-project-system',
    authDomain: 'geofencing-project-system.firebaseapp.com',
    storageBucket: 'geofencing-project-system.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaF8MKGImbqapP6vcR0siBYL6EgZGFOLM',
    appId: '1:986850440427:android:7f31cd39a491535019baae',
    messagingSenderId: '986850440427',
    projectId: 'geofencing-project-system',
    storageBucket: 'geofencing-project-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHcHXCgoHxregU7SnbGM5mrW9gfXlGOk0',
    appId: '1:986850440427:ios:3c50bdf2f0b3c74c19baae',
    messagingSenderId: '986850440427',
    projectId: 'geofencing-project-system',
    storageBucket: 'geofencing-project-system.appspot.com',
    iosClientId: '986850440427-vch3ub3crir5s2vedmc7sq5ksu2l5aa2.apps.googleusercontent.com',
    iosBundleId: 'com.example.geofence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHcHXCgoHxregU7SnbGM5mrW9gfXlGOk0',
    appId: '1:986850440427:ios:9243741b8268df6f19baae',
    messagingSenderId: '986850440427',
    projectId: 'geofencing-project-system',
    storageBucket: 'geofencing-project-system.appspot.com',
    iosClientId: '986850440427-3mai28kibp45ndfeduhf361ua959fq9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.geofence.RunnerTests',
  );
}
